blueprint:
  name: Aquaponics • Feeding activity monitor (FAM)
  description: >
    Sets a recent feeding flag for a configurable duration when the feeder switch turns on.
  domain: automation
  input:
    feeder_switch:
      name: Feeder switch
      selector:
        entity:
          domain: switch
    feeding_flag:
      name: Recent feeding flag
      selector:
        entity:
          domain: input_boolean
    window_minutes:
      name: Feeding window (minutes)
      default: 90
      selector:
        number:
          min: 1
          max: 360
          step: 1

trigger:
  - platform: state
    entity_id: !input feeder_switch
    to: "on"

action:
  - service: input_boolean.turn_on
    target:
      entity_id: !input feeding_flag
  - delay:
      minutes: !input window_minutes
  - service: input_boolean.turn_off
    target:
      entity_id: !input feeding_flag

mode: restart
